name: C/C++ CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: change configure permission
      run: chmod +x configure
    - name: configure
      run: ./configure
    - name: make
      run: make
